---
# Copyright(C) 2024 Team Prelab

name: "[Release]"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true

env:
  flutter_version: 3.22.2

jobs:
  ios:
    name: "<iOS> Build & Upload"
    runs-on: macos-14
    timeout-minutes: 30

    steps:
      - name: "Git Checkout"
        uses: actions/checkout@v4

      - name: "Set up Flutter"
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: stable

      - name: "Install dependencies"
        run: flutter pub get

      - name: "Xcode Version"
        run: xcodebuild -version

      - name: "Import AuthKey (.p8) of AppStore Connect API"
        env:
          APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
          APPLE_API_KEY: ${{ secrets.APPLE_API_KEY }}
        run: |
          mkdir ~/private_keys
          echo -n "$APPLE_API_KEY" | base64 --decode --output ~/private_keys/AuthKey_$APPLE_API_KEY_ID.p8

      - name: Run flutter build
        id: build
        run: flutter build ios --release --no-codesign

      - name: Archive by xcodebuild
        env:
          APPLE_API_ISSUER_ID: ${{ secrets.APPLE_API_ISSUER_ID }}
          APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
        run: xcodebuild archive CODE_SIGNING_ALLOWED=NO -workspace ./ios/Runner.xcworkspace -scheme Runner -configuration Release -archivePath ./build/ios/Runner.xcarchive

      - name: Export by xcodebuild
        env:
          APPLE_API_ISSUER_ID: ${{ secrets.APPLE_API_ISSUER_ID }}
          APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
        run: |
          ls -lh ~/private_keys
          xcodebuild -exportArchive -archivePath ./build/ios/Runner.xcarchive -exportPath ./build/ios/ipa -exportOptionsPlist ./ios/ExportOptions.plist -allowProvisioningUpdates -authenticationKeyIssuerID $APPLE_API_ISSUER_ID -authenticationKeyID $APPLE_API_KEY_ID -authenticationKeyPath ${HOME}/private_keys/AuthKey_$APPLE_API_KEY_ID.p8

      - name: "Upload to AppStore Connect"
        run: |
          ls -lh ~/private_keys
          KEY_ID=${{ secrets.APPLE_API_KEY_ID }}
          ISSUER_ID=${{ secrets.APPLE_API_ISSUER_ID }}
          xcrun altool --upload-app -f build/ios/ipa/ci_test.ipa -t ios --apiKey ${KEY_ID} --apiIssuer ${ISSUER_ID}
